---
- job:
    name: terraform-base-validate
    abstract: true
    pre-run: playbooks/pre-validate.yml
    run: playbooks/validate.yml

- job:
    name: terraform-base-validate-testbed-default
    parent: terraform-base-validate
    vars:
      name: testbed-default

- job:
    name: terraform-base-validate-testbed-managerless
    parent: terraform-base-validate
    vars:
      name: testbed-managerless

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - terraform-base-validate-testbed-default
        - terraform-base-validate-testbed-managerless
        - yamllint
    periodic-daily:
      jobs:
        - terraform-base-validate-testbed-default
        - terraform-base-validate-testbed-managerless
        - yamllint
