---
- job:
     name: terraform-base-validate
     abstract: true
     pre-run: playbooks/pre-validate.yml
     run: playbooks/validate.yml

- job:
    name: terraform-base-validate-testbed
    parent: terraform-base-validate
    vars:
      name: testbed

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - terraform-base-validate-testbed
        - yamllint
    periodic-daily:
      jobs:
        - terraform-base-validate
        - yamllint
